spring:
  application:
    name: ate-ngambek-be
  datasource:
    url: jdbc:postgresql://localhost:5432/ate-ngambek
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop   # Bisa diganti: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect