name: Build Native & Push Docker image

on:
  push:
    branches: [ "master" ]
    tags: [ "v*.*.*" ]

env:
  IMAGE_NAME: agungdh/agungdh.my.id-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #      - name: Login to Docker Hub
      #        uses: docker/login-action@v3
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #########################################################
      # Build & push ketika event-nya BRANCH (bukan tag)
      #########################################################
      - name: Build & push (branch)
        if: ${{ github.ref_type == 'branch' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: native.Dockerfile
          push: false
          tags: |
            ${{ env.IMAGE_NAME }}:native
            ${{ env.IMAGE_NAME }}:${{ github.sha }}-native

      #########################################################
      # Build & push khusus event TAG
      #########################################################
      - name: Build & push (tag)
        if: ${{ github.ref_type == 'tag' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: native.Dockerfile
          push: false
          tags: |
            ${{ env.IMAGE_NAME }}:native
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-native
            ${{ env.IMAGE_NAME }}:${{ github.sha }}-native
